### ISSUE TITLE
Elixir Research

### ISSUE THREAD

**Issue by milevy1** [milevy1/koroibos#10]
Read resources on these subjects:
- [x] #12 Elixir School - Basics
- [x] #11 Elixir School - Ecto
- [x] Spin up a new Phoenix project
- [x] Config a database (Postgres)
- [x] Migrations for db tables
- [x] DB Table Relationships
- [x] Interact with DB (Ecto)
- [x] Seed database with CSV
- [x] Route requests to controllers
- [x] See if there is something exists similar to "ActiveModel:Serializer"

**Comment by milevy1** [comment]
`--no-webpack`
Probably will not need webpack for Phoenix if its just a REST API
