### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by milevy1** [milevy1/koroibos#3]
Epic to track completion of required Endpoints

- [x] #5 GET api/v1/olympians
- [ ] #6 GET api/v1/olympians?age=youngest
- [ ] #6 GET api/v1/olympians?age=oldest
- [ ] #7 GET api/v1/olympian_stats
- [ ] #8 GET api/v1/events
- [ ] #9 GET api/v1/events/:id/medalists

Insert extra ones you think of here:
....
